
spring:
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
  flyway:
    locations: classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8080
  managementPort: 8081

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: ${ROOT_LOGGING_LEVEL:INFO}
    org.apache.http: WARN
#    org.springframework: DEBUG

accessToken:
  validityInSeconds: ${ACCESS_TOKEN_VALIDITY:86400}

govNotify:
  key: ${GOV_NOTIFY_API_KEY:key}
  template:
    invite: ${GOV_NOTIFY_INVITE_TEMPLATE_ID:template}
    reset: ${GOV_NOTIFY_RESET_TEMPLATE_ID:template}
    resetSuccessful: ${GOV_NOTIFY_RESET_SUCCESSFUL_TEMPLATE_ID:template}
    passwordUpdate: ${GOV_NOTIFY_PASSWORD_UPDATE_TEMPLATE_ID:13c2b9ac-4ad0-449f-b43b-57c04fc88b1d}

invite:
  url: ${INVITE_SIGNUP_URL:http://localhost:8080/signup/%s}
  validityInSeconds: ${INVITE_VALIDITY:259200}
  whitelist:
    domains: example.org, domain.org

reset:
  url: ${RESET_URL:http://localhost:8080/reset/%s}
  validityInSeconds: ${RESET_VALIDITY:86400}

accountValidation:
  passwordPattern: ${PASSWORD_PATTERN:^(?:(?=.*[a-z])(?:(?=.*[A-Z])(?=.*[\\d\\W]))).{8,}$}

account:
  lockout:
    maxAttempt: 5

lpg:
  uiUrl: ${LPG_UI_URL:http://localhost:3001}

---

spring:
  profiles: production
  thymeleaf:
    cache: true
  datasource:
    url: ${DATASOURCE:jdbc:mysql://localhost:3306/oauth2?user=root&password=password&useSSL=false}
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        enable_lazy_load_no_trans: true
